name: Front End CI/CD

on:
  push:
    branches:
    - main
    paths:
    - 'website/**'  #This is the folder to trigger changes in website directory


jobs:
  deploy-front-end-code:
    runs-on: ubuntu-latest
    environment: Portfolio

    steps:
    #Step 1: To check out code
    - name: Checkout code
      uses: actions/checkout@v4

    #Step 2: Upload files to s3 from website directory
    - name: Upload files to s3
      run: |
        aws s3 cp ./website s3://${{ secrets.AWS_S3_BUCKET }} --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.S3_REGION }}

    #Step 3: Invalidation for Cloudfront cache after new upload
    - name: Invalidations in Cloudfront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS_REGION: ${{ secrets.CF_REGION }}

